INSERT INTO country(name, code_name) VALUES ('Australia', 'AU'),
('Canada', 'CA'),
('France', 'FR'),
('Hong Kong', 'HK'),
('Iceland', 'IC'),
('Japan', 'JP'),
('Nepal', 'NP'),
('Russian Federation', 'RU'),
('Sweden', 'SE'),
('Switzerland', 'CH'),
('United Kingdom', 'GB'),
('United States', 'US');